#!/bin/bash
# [actualizar-firefox] -Luis GuLo-
# Permite no hacer descarga y usar version de /tmp
# tiene que recibir '--install'
PARAMETRO="$1"
# Localizar ultima version de Firefox en internet
echo ""
echo "Chequeando ultima version de Firefox disponible ..."
wget -q https://www.mozilla.org/es-ES/firefox/new/ -O /tmp/version.firefox
netversion=`grep 'data-latest-firefox' /tmp/version.firefox |awk -F 'data-latest-firefox="' '{print $2}'|awk -F '"' '{print $1}'`
antversion=`/opt/firefox/firefox --version |awk -F 'Mozilla Firefox ' '{print $2}'`

if [ "$netversion" == "" ] ; then
	echo "Imposible comprobar ultima version disponible en Internet"
	exit 404
fi

if [ "$PARAMETRO" == "--install" ]; then
	# FICHERO en /tmp
	echo "Usando fichero pre-descargado en /tmp"
	PARCHEAR="SI"
else
	# Fichero de Internet
	if [ "$netversion" == "$antversion" ] ; then
	   echo "Su versión de Firefox $antversion es la última disponible"
	   echo "No es necesaria la actualizacion"
	   echo "------------------------------------------------------------------"
	   PARCHEAR="NO"
	else
		# detectamos arquitectura (64 vs 32)
		arquitectura=`arch` 
		# Se localiza ultima version estable y se descarga
		sudo rm -rf /tmp/FirefoxQuantum.tar.bz2 2> /dev/null
		echo "Descargando ultima version para su arquitectura $arquitectura"
		if [ "$arquitectura" == "x86_64" ] ; then ARQ='linux64'; else ARQ='linux'; fi
		wget -q -O /tmp/FirefoxQuantum.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=$ARQ&lang=es-ES"
		PARCHEAR="SI"
	fi
fi
if [ "$PARCHEAR" == "SI" ] ; then
	# Intalamos lo descargado previamente (offline) o lo ultimo descargado
	ultimo=/tmp/FirefoxQuantum.tar.bz2
	cd /opt/
	#Borramos anterior
	sudo rm -rf firefox*
	# Descomprimir
	echo "Descomprimiendo e instalando..."
	sudo tar xjfp $ultimo 2>/dev/null

	if [ "$arquitectura" == "x86_64" ] ; then 
		echo "Ajustando libreria libmozsqlite3"
		# Enlace para libmozsqlite3
		sudo ln -s /opt/firefox/libmozsqlite3.so /lib/x86_64-linux-gnu/. 2>/dev/null 
	fi
	echo "Ajustando 'alternatives' para Firefox"
	sudo update-alternatives --force --install /usr/bin/firefox firefox  /opt/firefox/firefox 1
	suversion=`firefox --version`
	echo "--------------------------------------------"
	echo "Firefox $antversion se ha instalado/actualizado a:"
	echo $suversion
	echo "--------------------------------------------"
fi	
